<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML & DL</b></center>

<center><b><h1>Lab - 8</b></center>    
<pre>

# Step 1: Import Libraries
This step imports all necessary libraries for data processing, visualization, and machine learning.

In [1]:
import pandas as pd
import seaborn as sb
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split

# Step 2: Load the Dataset
Load Given dataset -  heart.csv

In [2]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

# Step 3: Data Overview
In this step, we examine the dataset structure, summary statistics, and check for missing values.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [4]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [5]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(723)

In [7]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

# Step 4: Univariate Analysis
Here we visualize the distribution of each feature using histograms.

In [8]:
%matplotlib qt

In [9]:
df.hist(figsize=(12,12))

array([[<Axes: title={'center': 'age'}>, <Axes: title={'center': 'sex'}>,
        <Axes: title={'center': 'cp'}>,
        <Axes: title={'center': 'trestbps'}>],
       [<Axes: title={'center': 'chol'}>,
        <Axes: title={'center': 'fbs'}>,
        <Axes: title={'center': 'restecg'}>,
        <Axes: title={'center': 'thalach'}>],
       [<Axes: title={'center': 'exang'}>,
        <Axes: title={'center': 'oldpeak'}>,
        <Axes: title={'center': 'slope'}>,
        <Axes: title={'center': 'ca'}>],
       [<Axes: title={'center': 'thal'}>,
        <Axes: title={'center': 'target'}>, <Axes: >, <Axes: >]],
      dtype=object)

# Step 5: Bivariate Analysis
This step involves exploring the correlations between features using a heatmap.

In [10]:
plt.figure(figsize=(10, 7))
sb.heatmap(df.corr(), annot=True)
plt.show()

# Step 6: Outlier Detection
We visualize potential outliers using boxplots.

In [11]:
df.boxplot()

# Step 7: Split Data into Training and Testing Sets
The dataset is split into training and testing sets for model evaluation.

In [12]:
x = df.drop('target',axis=1)
y = df['target']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=80)

# Step 8: Train Decision Tree
We train a Decision Tree Classifier on the training data. You have to also check for KNeighborsClassifier and  GaussianNB

In [14]:

from sklearn.tree import DecisionTreeClassifier

In [15]:
model = DecisionTreeClassifier()

In [16]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [17]:
y_pred = model.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test, y_pred)

0.7704918032786885

# Cross Validation

In [20]:
from sklearn.model_selection import KFold

In [21]:
k = KFold(n_splits=10)

In [22]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [30]:
for train_index, test_index in k.split(x):
    x_train, x_test, = x.values[train_index], x.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    model1 = DecisionTreeClassifier()
    model1.fit(x_train, y_train)
    print(model1.score(x_test, y_test))

0.8064516129032258
0.6774193548387096
0.8
0.7
0.8666666666666667
0.7
0.8333333333333334
0.7666666666666667
0.7333333333333333
0.8

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(model,x,y,cv=10)

array([0.80645161, 0.70967742, 0.8       , 0.76666667, 0.83333333,
       0.83333333, 0.86666667, 0.8       , 0.73333333, 0.76666667])

In [31]:
import numpy as np

In [32]:
x1 = np.arange(1,11).reshape(-1,1)
y1 = np.array([0,1,0,1,0,1,0,1,0,1])

In [34]:
for i, j in k.split(x1):
    print('<------>')
    print(x1[i])
    print(x1[j])
    x_train, x_test = x1[i], x1[j]
    y_test, y_test = y1[i], y1[j]

<------>
[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[1]]
<------>
[[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[2]]
<------>
[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[3]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[4]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[5]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[6]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
[[7]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]]
[[8]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]]
[[9]]
<------>
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10]]

# BS4 | web Scraping to get Data

In [35]:
import requests
import bs4

In [36]:
req = requests.get('https://darshan.ac.in/faculty-list/btech-computer')

In [ ]:
req.status_code

200

In [41]:
soup = bs4.BeautifulSoup(req.text, "html.parser")

In [42]:
data = soup.select("body > main > div:nth-child(5) > div > div > div > div > div")

In [44]:
len(data)

31

In [58]:
for f in data:
    name = f.select('h2')[0].get_text().strip()
    d1 = f.select('span')[0].text.strip()
    d2 = f.select('span')[1].text.strip()
    d3 = f.select('span')[2].text.strip()
    d4 = f.select('span')[3].text.strip()
    print(f'{name} ---> {d1}, {d2}, {d3} = {d4}')

Dr. Gopi Sanghani ---> Dean - Faculty of Computer Science, Ph.D. , M.E. (CE), Experience = 25+ Years
Dr. Nilesh Gambhava ---> Professor, Ph.D. , M.E. (CE), Experience = 23+ Years
Dr. Pradyumansinh Jadeja ---> Professor, Ph.D., M.E. (CE), Experience = 20+ Years
Prof. Maulik Trivedi ---> Assistant Professor, Ph.D.(Pursuing), M.Tech.(CSE), Experience = 17+ Years
Prof. Firoz Sherasiya ---> Assistant Professor, Ph.D.(Pursuing), M.E. (CE), Experience = 21+ Years
Prof. Rupesh Vaishnav ---> Assistant Professor, Ph.D. (Pursuing), M.E. (CE), Experience = 17+ Years
Prof. Arjun Bala ---> Assistant Professor, Ph.D.(Pursuing), M.Tech.(CSE), Experience = 15+ Years
Prof. Naimish Vadodariya ---> Assistant Professor, Ph.D. (Pursuing), M.E. (CE), Experience = 12+ Years
Prof. Vaseem Ghada ---> Assistant Professor, Ph.D. (Pursuing), M.Tech (ICT), Experience = 16+ Years
Dr. Sharon Mohtra ---> Assistant Professor, PhD. in Computer Science, MCA, BCA, Experience = 24+ Years
Prof. Dixita Kagathara ---> Assistant Professor, Ph.D.(Pursuing), M.Tech. (Web Technology), Experience = 16+ Years
Prof. Swati Sharma ---> Assistant Professor, PhD(Pursuing), M.Tech. (CSE), Experience = 17+ Years
Prof. Mayur Padia ---> Assistant Professor, M.E. (CE), Experience = 17+ Years
Prof. Ashok Badresiya ---> Assistant Professor, Ph.D. (Pursuing), M.E. (CE), Experience = 12+ Years
Prof. UmeshKumar Thoriya ---> Assistant Professor, M.Tech. (CSE), Experience = 12+ Years
Prof. Jayesh Vagadiya ---> Assistant Professor, M.E (CE), Experience = 10+ Years
Prof. Krunal Vyas ---> Assistant Professor, Ph.D. (Pursuing), M.Tech. (ICT), Experience = 12+ Years
Prof. Rajkumar Gondaliya ---> Assistant Professor, M.E. (CE), Experience = 9+ Years
Prof. Mehul Bhundiya ---> Assistant Professor, M.E. (CE), Experience = 11+ Years
Prof. Jay Dhamsaniya ---> Assistant Professor, PG Diploma (Software Development), B.Tech. (E.C.), Experience = 13+ Years
Prof. Vishal Kansagara ---> Assistant Professor, M. TECH. (ICT), Experience = 11+ Years
Prof. Shruti Maniar ---> Assistant Professor, ME(CE),BE(IT), Experience = 9+ Years
Prof. Dharmik Vasiyani ---> Assistant Professor, ME(CE), Experience = 8+ Years
Prof. Devangi Kotak ---> Assistant Professor, M. Tech(CS), BE(IT), Diploma I.T., Experience = 17+ Years
Prof. Bhushan Joshi ---> Assistant Professor, M.E. (EC), Experience = 8+ Years
Prof. Hemang Chath ---> Assistant Professor, Ph.D. (Pursuing), M.E. (CE), Experience = 15+ Years
Prof. Charvin Kothia ---> Assistant Professor, M.Tech. (CE), Experience = 6+ Years
Prof. Madhuresh Fichadiya ---> Assistant Professor, M.Tech (Pursuing), B.E.(CE), Experience = 4+ Years
Prof. Mehuli Domadiya ---> Teaching Assistant, M.Tech (Pursuing), B.E.(CE), Experience = 1+ Years
Prof. Sejal Gupta ---> Teaching Assistant, B.E.(CE), Experience = 1+ Years
Prof. SAMIR KARIYA ---> Assistant Professor, Ph.D.(Pursuing), M.Tech.(CSE), Experience = 12+ Years